services:
  researchgraph:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/researchgraph:cached
    environment:
      - PYTHONPATH=/workspaces/researchgraph/src
#   researchgraph-gpu:
#     build:
#       context: ../
#       dockerfile: ./.devcontainer/dev-gpu.Dockerfile
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: all
#               capabilities: [gpu]
#     env_file:
#       - ../.env
#     volumes:
#       - ..:/workspaces/researchgraph:cached
#     environment:
#       - PYTHONPATH=/workspaces/researchgraph/src
#       - NVIDIA_VISIBLE_DEVICES=all
#       - NVIDIA_DRIVER_CAPABILITIES=compute,utility
