services:
  researchgraph:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/researchgraph:cached
    environment:
      - PYTHONPATH=/workspaces/researchgraph/src
