name: Keep Streamlit Alive

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit App
        run: curl -s https://researchgraph.streamlit.app/
