name: RetrievePaperSubgraph

on:
  workflow_dispatch:

jobs:
  do-nothing:
    name: Do Nothing Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "This workflow does nothing."
