name: ResearchGraph Nodes Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: 
      - "src/**"

defaults:
  run:
    shell: bash

jobs:
  test-llmnodes:
    name: Test of LLMNodes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

      - name: Verify uv installation
        run: uv --version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Print PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH"

      - name: Run pytest
        run: uv run pytest test/test_llmnodes.py

      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip
  
  test-retrievenodes:
    name: Test of RetrieveNodes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

      - name: Verify uv installation
        run: uv --version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Print PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH"

      - name: Create necessary directories
        run: mkdir -p /workspaces/researchgraph/data

      - name: Run pytest
        run: uv run pytest test/test_retrievenodes.py

      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip
