# name: ResearchGraph WriterSubgraph Test

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]
#     paths: [
#       'src/researchgraph/writer_subgraph/**', 
#       'test/writer_subgraph/**',
#       '.github/workflows/pytest_writer_subgraph.yml'
#       ]

# defaults:
#   run:
#     shell: bash

# job:
#   test-search_papers_node:
#     name: Test of SearchPapersNode
#     runs-on: ubuntu-latest
#     env:
#       SAVE_DIR: ${{ github.workspace }}/save_dir
#       S2_API_Key: ${{ secrets.S2_API_Key }}
#     timeout-minutes: 5
#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"
#           cache: "pip"

#       - name: Install uv
#         run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

#       - name: Verify uv installation
#         run: uv --version

#       - name: Set PYTHONPATH
#         run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

#       - name: Print PYTHONPATH
#         run: echo "PYTHONPATH=$PYTHONPATH"
        
#       - name: Create Directory
#         run: mkdir -p $SAVE_DIR
        
#       - name: Run pytest
#         run: uv run pytest test/retrieve_paper_subgraph/test_search_papers_node.py

#       - name: Ensure pip cache folder exists
#         run: mkdir -p /home/runner/.cache/pip

#   test_retrieve_arxiv_text_node:
#     name: Test of RetrieveArxivTextNode
#     runs-on: ubuntu-latest
#     env:
#       SAVE_DIR: ${{ github.workspace }}/save_dir
#     timeout-minutes: 5
#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"
#           cache: "pip"

#       - name: Install uv
#         run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

#       - name: Verify uv installation
#         run: uv --version

#       - name: Set PYTHONPATH
#         run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

#       - name: Print PYTHONPATH
#         run: echo "PYTHONPATH=$PYTHONPATH"
        
#       - name: Create Directory
#         run: mkdir -p $SAVE_DIR
        
#       - name: Run pytest
#         run: uv run pytest test/retrieve_paper_subgraph/test_retrieve_arxiv_text_node.py

#       - name: Ensure pip cache folder exists
#         run: mkdir -p /home/runner/.cache/pip

#   test-extract_github_urls_node:
#     name: Test of ExtractGithubUrlsNode
#     runs-on: ubuntu-latest
#     env:
#       SAVE_DIR: ${{ github.workspace }}/save_dir
#     timeout-minutes: 5
#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"
#           cache: "pip"

#       - name: Install uv
#         run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

#       - name: Verify uv installation
#         run: uv --version

#       - name: Set PYTHONPATH
#         run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

#       - name: Print PYTHONPATH
#         run: echo "PYTHONPATH=$PYTHONPATH"
        
#       - name: Create Directory
#         run: mkdir -p $SAVE_DIR
        
#       - name: Run pytest
#         run: uv run pytest test/retrieve_paper_subgraph/test_extract_github_url_node.py

#       - name: Ensure pip cache folder exists
#         run: mkdir -p /home/runner/.cache/pip
