name: Test

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]
#     paths: [src/**]
on:
  push:

jobs:
  test:
    name: Test of LLMNodes
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1

      - name: Verify uv installation
        run: uv --version

      - name: Print PATH
        run: echo $PATH

      - name: Run pytest
        run: uv run pytest src/researchgraph/tests/test_llmnodes.py
