name: Test

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]
#     paths: [src/**]
on:
  push:

jobs:
  test:
    name: Test of LLMNodes
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: python -m pytest
