name: Test
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - run: echo "&{OPENAI_API_KEY}"
      - uses: actions/checkout@v2
