name: ResearchPreparationSubgraph

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: [
      'src/airas/research_preparation_subgraph/**',
      'tests/research_preparation_subgraph/**',
      'tests/unit/research_preparation_subgraph/**',
      '.github/workflows/test_research_preparation_subgraph.yml'
    ]

defaults:
  run:
    shell: bash

jobs:
  test-research-preparation-subgraph:
    name: ResearchPreparationSubgraph Components
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - test_name: check_github_repository
            test_file: tests/unit/research_preparation_subgraph/test_check_github_repository.py
          - test_name: fork_repository
            test_file: tests/unit/research_preparation_subgraph/test_fork_repository.py
          - test_name: check_branch_existence
            test_file: tests/unit/research_preparation_subgraph/test_check_branch_existence.py
          - test_name: create_branch
            test_file: tests/unit/research_preparation_subgraph/test_create_branch.py
          - test_name: retrieve_main_branch_sha
            test_file: tests/unit/research_preparation_subgraph/test_retrieve_main_branch_sha.py
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
      SAVE_DIR: ${{ github.workspace }}/save_dir
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1
          uv --version
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV
      - name: Create Directory
        run: mkdir -p $SAVE_DIR
      - name: Run pytest with coverage
        run: uv run pytest --cov=airas.research_preparation_subgraph --cov-branch --cov-report=term-missing -v ${{ matrix.test_file }}
      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip
